apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-nodejs-pipeline
spec:
  params:
  - name: deployment-name
    type: string
    description: name of the deployment to be patched
  - name: IMAGE
    type: string
    description: Location of the repo where image has to be pushed
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/lebrisg/maps7
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: s2i
    taskRef:
      name: s2i-nodejs
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-workspace
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - fetch-repository
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - s2i
  - name: update-deployment
    taskRef:
      name: update-deployment
    params:
    - name: deployment
      value: $(params.deployment-name)
    - name: IMAGE
      value: $(params.IMAGE)
    runAfter:
    - apply-manifests
