apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-trivy 
spec:
  params:
  - name: IMAGE
    description: Location of image to be scanned 
    type: string
  workspaces:
  - name: source-dir
  steps:
  - name: image-scan
    image: aquasec/trivy 
    workingDir: $(workspaces.source-dir.path)
    command:
    - trivy
    args:
#      - --skip-update 
      - --debug
      - --exit-code
      - "1" 
      - --input
      - "$(inputs.params.IMAGE)" 
