apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: maps7-monitor
  name: maps7-monitor
  namespace: maps7 
spec:
  endpoints:
    - interval: 30s
  port: http
  scheme: http
  selector:
    matchLabels:
      project: maps7
